[project]
name = "datahackdays25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "pandas>=2.2.3",
    "pypdf2>=3.0.1",
    "qdrant-client>=1.14.2",
    "requests>=2.32.3",
]
